[database]
name = '' #provide your db name
user ='' #provide your db user name
password ='' #provide your password
host ='' #provide your host
port ='' #provide you port number

[image_validation]
image_size = 1145728
image_format = [".jpg", ".png",".jpeg"]
image_size_error = "Please upload an image file smaller than 1MB."
image_format_error = "Please upload a JPG or PNG image."
image_empty_error = "Image not exists, please upload one image..!"